print("Nama = Lodero Kalsara")
print("NIM  = I0322068")
print("Asal = Jakarta")
print("===========================")
print("Saya berasal dari Jakarta yaitu ibukota Indonesia")
print("Jakarta biasa disebut juga dengan kota metropolitan")
print("Jakarta adalah kota terpadat di Indonesia dan menyebabkan kemacetan dijalanan")
print("===========================")
print("Harapan saya setelah keluar dari Teknik Industri adalah saya mendapat pekerjaan yang saya inginkan")